spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: root
    url: jdbc:mysql://localhost:3306/contact_manager
    username: root
  jpa:
    hibernate:
      ddl-auto: 'update    '
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
